/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'digitalGraphics' : null } |
  { 'logoDesign' : null } |
  { 'printMedia' : null } |
  { 'uiuxDesign' : null } |
  { 'motionGraphics' : null } |
  { 'branding' : null };
export interface ContactSubmission {
  'id' : bigint,
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface PortfolioItem {
  'id' : string,
  'title' : string,
  'featured' : boolean,
  'description' : string,
  'imageUrl' : ExternalBlob,
  'category' : Category,
}
export interface Service {
  'id' : bigint,
  'title' : string,
  'icon' : string,
  'description' : string,
}
export interface TeamMember {
  'id' : string,
  'bio' : string,
  'name' : string,
  'role' : string,
  'imageUrl' : ExternalBlob,
}
export interface Testimonial {
  'id' : bigint,
  'name' : string,
  'role' : string,
  'quote' : string,
  'company' : string,
  'rating' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPortfolioItem' : ActorMethod<
    [string, string, Category, string, ExternalBlob, boolean],
    undefined
  >,
  'addService' : ActorMethod<[string, string, string], undefined>,
  'addTeamMember' : ActorMethod<
    [string, string, string, string, ExternalBlob],
    undefined
  >,
  'addTestimonial' : ActorMethod<
    [string, string, string, string, bigint],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deletePortfolioItem' : ActorMethod<[string], undefined>,
  'deleteService' : ActorMethod<[bigint], undefined>,
  'deleteTeamMember' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getFeaturedPortfolioItems' : ActorMethod<[], Array<PortfolioItem>>,
  'getPortfolioItems' : ActorMethod<[], Array<PortfolioItem>>,
  'getPortfolioItemsByCategory' : ActorMethod<[Category], Array<PortfolioItem>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeTestimonial' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'updatePortfolioItem' : ActorMethod<
    [string, string, Category, string, ExternalBlob, boolean],
    undefined
  >,
  'updateService' : ActorMethod<[bigint, string, string, string], undefined>,
  'updateTeamMember' : ActorMethod<
    [string, string, string, string, ExternalBlob],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];